### ISSUE TITLE
Some improvement proposals

### ISSUE THREAD

**Issue by alexkuz** [alexkuz/react-json-tree#43]
1. **Get rid of previousData prop**. If I got it right, this prop is used to highlight changed data. To me this behaviour looks too specific - I guess user should be able to apply style himself if he needs to.

2. **Better theming**. I've added `getLabelStyle` etc. methods some time ago, but I'm not happy about them :) I like the approach I used in `redux-devtools-insopector` more, which is based upon `react-themeable` solution with an extension for `base16` theming:
- if `theme` is an object with `baseNN` keys, it is treated as `base16` theme and is used with default styles;
- if `theme` has `string` values, they're considered classnames;
- if values are objects, they're considered styles.

If there's a necessity, we can also allow functions as values (to provide `type` and `expanded` parameters in out case), though I'm not 100% sure about that.

The signature would be like this then:
```js
createStyling(theme: Object, createDefaultStyles: Function, key: String, ...args) -> { style: { ... }, className: '...' }

// which can be splitted, if we use currying:

const styling = createStyling(theme, createDefaultStyles);

return (
  <div {...styling('item', type, expanded)>
    <div {...styling('label', type, expanded)}></div>
    <div {...styling('value', type, expanded)}></div>
  </div>
);
```

What do you think? @gaearon @chibicode

**Comment by chibicode** [comment]
@alexkuz 

> Get rid of previousData prop. If I got it right, this prop is used to highlight changed data. To me this behaviour looks too specific - I guess user should be able to apply style himself if he needs to.

Right, and this prop has been around since the very first version written by the original author. I agree that it's too specific: 
https://github.com/chibicode/react-json-tree/blob/0d3132fc54f3e5679a0ae6da7f7c12c7113bdfeb/src/JSONValueNode.js#L33-L39
I'm wondering if `valueRenderer` be re-purposed for this for those who need to highlight changed data.

> Better theming. I've added getLabelStyle etc. methods some time ago, but I'm not happy about them :) I like the approach I used in redux-devtools-insopector more, which is based upon react-themeable solution with an extension for base16 theming

I took a brief look at [this file](https://github.com/alexkuz/redux-devtools-inspector/blob/master/src/createDefaultTheme.js) and [this file](https://github.com/alexkuz/redux-devtools-inspector/commit/e56b990a077c0bba1835400ebe80d7a381116dc2) on redux-devtools-inspector and it sounds like a good idea.

---

@alexkuz One last note - I've stopped using `react-json-tree` within the app I'm building (my app used to have a JSON viewer, but I got rid of it - tho my app still uses `redux-devtools`) and I haven't been able to spend much time maintaining this repo. Since your `redux-devtools-inspector` seems like one of the core use cases of `react-json-tree`, if you don't mind, I'd be happy to transfer the ownership of this repo to you. I'd still would be happy to help - I've been wanting to write `enzyme` tests when I get time.

**Comment by alexkuz** [comment]
> Since your redux-devtools-inspector seems like one of the core use cases of react-json-tree, if you don't mind, I'd be happy to transfer the ownership of this repo to you. 

That sounds reasonable, I'm ok with that :) Thank you!

**Comment by chibicode** [comment]
@alexkuz thank YOU! Could you delete your fork? Then I'll be able to transfer it to you

**Comment by alexkuz** [comment]
Done!

**Comment by chibicode** [comment]
@alexkuz requested!

**Comment by alexkuz** [comment]
@chibicode I'm not sure how it works. Do I need to accept it somewhere?

**Comment by alexkuz** [comment]
Ah, nevermind, it's in the mail.
